"use client"

import * as React from "react"

export type Language = "en" | "vi"

type LanguageContextType = {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.campaign": "Campaign",
    "nav.campaign.list": "List",
    "nav.campaign.create": "Create",
    "nav.qrcode": "QR Code",
    "nav.qrcode.list": "List",
    "nav.qrcode.create": "Create",
    "nav.ggServices": "GG Services",
    "nav.ggServices.setup": "Setup",
    "nav.ggServices.sync": "Sync to Calendar",
    "nav.ggServices.import": "Import from Calendar",
    "nav.ggServices.remove": "Remove Event",
    "nav.analytics": "Analytics",
    "nav.analytics.campaign": "Analyze by Campaign",
    "nav.report": "Report",
    "nav.report.export": "Export Report to Client",
    "nav.accountManagement": "Account Management",
    "nav.accountManagement.employees": "Employee List",
    "nav.navigation": "Navigation",

    // User Menu
    "user.profile": "Profile",
    "user.settings": "Settings",
    "user.toggleTheme": "Theme",
    "user.switchLanguage": "Language",
    "user.logout": "Log out",
    "user.language.en": "English",
    "user.language.vi": "Vietnamese",

    // Breadcrumbs
    "breadcrumb.home": "Home",
    "breadcrumb.dashboard": "Dashboard",
    "breadcrumb.campaigns": "Campaigns",
    "breadcrumb.googleServices": "Google Services",
    "breadcrumb.reports": "Reports",
    "breadcrumb.qrcodes": "QR Codes",
    "breadcrumb.settings": "Settings",
    "breadcrumb.accounts": "Accounts",
    "breadcrumb.employees": "Employees",
    "breadcrumb.create": "Create",
    "breadcrumb.setup": "Setup",
    "breadcrumb.sync": "Sync",
    "breadcrumb.import": "Import",
    "breadcrumb.undo": "Undo",
    "breadcrumb.export": "Export",

    // Common
    "common.notifications": "Notifications",
    "common.search": "Search",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.create": "Create",
    "common.loading": "Loading...",
    "common.noData": "No data available",
    "common.actions": "Actions",
    "common.status": "Status",
    "common.name": "Name",
    "common.description": "Description",
    "common.date": "Date",
    "common.active": "Active",
    "common.inactive": "Inactive",
    "common.paused": "Paused",
    "common.completed": "Completed",
    "common.planned": "Planned",
    "common.all": "All",
    "common.filter": "Filter",
    "common.export": "Export",
    "common.import": "Import",
    "common.refresh": "Refresh",
    "common.back": "Back",
    "common.next": "Next",
    "common.previous": "Previous",
    "common.submit": "Submit",
    "common.reset": "Reset",
    "common.close": "Close",
    "common.confirm": "Confirm",
    "common.yes": "Yes",
    "common.no": "No",
    "common.pro": "Pro",
    "common.preview": "Preview",
    "common.enabled": "Enabled",
    "common.disabled": "Disabled",

    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.welcome": "Welcome back",
    "dashboard.overview": "Overview",
    "dashboard.totalCampaigns": "Total Campaigns",
    "dashboard.activeQRCodes": "Active QR Codes",
    "dashboard.totalScans": "Total Scans",
    "dashboard.recentActivity": "Recent Activity",

    // Campaigns
    "campaigns.title": "Campaigns",
    "campaigns.create": "Create Campaign",
    "campaigns.edit": "Edit Campaign",
    "campaigns.delete": "Delete Campaign",
    "campaigns.name": "Campaign Name",
    "campaigns.status": "Status",
    "campaigns.startDate": "Start Date",
    "campaigns.endDate": "End Date",
    "campaigns.scans": "Scans",
    "campaigns.qrCodes": "QR Codes",
    "campaigns.noResults": "No campaigns found",

    // QR Codes
    "qrcodes.title": "QR Codes",
    "qrcodes.create": "Create QR Code",
    "qrcodes.edit": "Edit QR Code",
    "qrcodes.delete": "Delete QR Code",
    "qrcodes.download": "Download",
    "qrcodes.preview": "Preview",
    "qrcodes.scans": "Total Scans",
    "qrcodes.destination": "Destination URL",
    "qrcodes.noResults": "No QR codes found",

    // Settings
    "settings.title": "Settings",
    "settings.subtitle": "Manage your account settings and preferences",
    "settings.profile": "Profile Information",
    "settings.profileDesc": "Update your personal information and contact details",
    "settings.account": "Account",
    "settings.notifications": "Notification Preferences",
    "settings.notificationsDesc": "Choose what notifications you want to receive",
    "settings.language": "Language",
    "settings.theme": "Theme",
    "settings.username": "Username",
    "settings.fullName": "Full Name",
    "settings.phone": "Phone Number",
    "settings.email": "Email",
    "settings.saveChanges": "Save Changes",
    "settings.changePassword": "Change Password",
    "settings.changePasswordDesc": "Update your password to keep your account secure",
    "settings.currentPassword": "Current Password",
    "settings.newPassword": "New Password",
    "settings.confirmNewPassword": "Confirm New Password",
    "settings.updatePassword": "Update Password",
    "settings.emailAlerts": "Email Alerts",
    "settings.emailAlertsDesc": "Receive email notifications for important updates",
    "settings.campaignUpdates": "Campaign Updates",
    "settings.campaignUpdatesDesc": "Get notified when campaigns are created or modified",
    "settings.weeklyReports": "Weekly Reports",
    "settings.weeklyReportsDesc": "Receive a weekly summary of your campaign performance",
    "settings.dangerZone": "Danger Zone",
    "settings.dangerZoneDesc": "Irreversible actions for your account",
    "settings.logoutDesc": "Log out of your account",
    "settings.logoutSubDesc": "You will be redirected to the login page",
    "settings.logoutConfirmTitle": "Are you sure you want to log out?",
    "settings.logoutConfirmDesc": "You will need to sign in again to access your dashboard.",
    "settings.passwordIncorrect": "Current password is incorrect",
    "settings.passwordTooShort": "New password must be at least 8 characters",
    "settings.passwordMismatch": "New passwords do not match",

    // Campaigns Page
    "campaignsPage.title": "Campaigns",
    "campaignsPage.subtitle": "Manage and track your QR code marketing campaigns",
    "campaignsPage.createCampaign": "Create Campaign",
    "campaignsPage.searchPlaceholder": "Search by name, description, or creator...",
    "campaignsPage.allStatus": "All Status",
    "campaignsPage.active": "Active",
    "campaignsPage.paused": "Paused",
    "campaignsPage.campaignName": "Campaign Name",
    "campaignsPage.createdBy": "Created By",
    "campaignsPage.createAt": "Created At",
    "campaignsPage.dateRange": "Date Range",
    "campaignsPage.integrations": "Integrations",
    "campaignsPage.calendar": "Calendar",
    "campaignsPage.viewDetails": "View Details",
    "campaignsPage.editCampaign": "Edit Campaign",
    "campaignsPage.deleteCampaign": "Delete Campaign",
    "campaignsPage.deleteTitle": "Delete Campaign",
    "campaignsPage.deleteConfirm": "Are you sure you want to delete",
    "campaignsPage.deleteWarning": "This action cannot be undone.",
    "campaignsPage.noCampaigns": "No campaigns found",

    // QR Codes Page
    "qrcodesPage.title": "QR Codes",
    "qrcodesPage.subtitle": "Manage and track all your QR codes across campaigns",
    "qrcodesPage.createQRCode": "Create QR Code",
    "qrcodesPage.searchPlaceholder": "Search by name, URL, or campaign...",
    "qrcodesPage.allCampaigns": "All Campaigns",
    "qrcodesPage.allStatus": "All Status",
    "qrcodesPage.active": "Active",
    "qrcodesPage.inactive": "Inactive",
    "qrcodesPage.createdBy": "Created By",
    "qrcodesPage.qrCodeName": "QR Code Name",
    "qrcodesPage.campaign": "Campaign",
    "qrcodesPage.destinationUrl": "Destination URL",
    "qrcodesPage.scans": "Scans",
    "qrcodesPage.unique": "unique",
    "qrcodesPage.created": "Created",
    "qrcodesPage.lastScan": "Last scan",
    "qrcodesPage.viewQRCode": "View QR Code",
    "qrcodesPage.downloadQRCode": "Download QR Code",
    "qrcodesPage.copyLink": "Copy Link",
    "qrcodesPage.copied": "Copied!",
    "qrcodesPage.editQRCode": "Edit QR Code",
    "qrcodesPage.deleteQRCode": "Delete QR Code",
    "qrcodesPage.deleteTitle": "Delete QR Code",
    "qrcodesPage.deleteConfirm": "Are you sure you want to delete this QR code?",
    "qrcodesPage.deleteWarning": "This action cannot be undone.",
    "qrcodesPage.noQRCodes": "No QR codes found",
    "qrcodesPage.qrDetails": "QR Code Details",
    "qrcodesPage.downloadPng": "Download PNG",
    "qrcodesPage.downloadSvg": "Download SVG",
    "qrcodesPage.scanQr": "Scan to visit URL",

    // Create QR Form (additional keys)
    "qrcodesPage.selectCampaign": "Select Campaign",
    "qrcodesPage.selectCampaignPlaceholder": "Choose a campaign",
    "qrcodesPage.qrCodeDetails": "QR Code Details",
    "qrcodesPage.qrCodeNameLabel": "QR Code Name",
    "qrcodesPage.descriptionLabel": "Description",
    "qrcodesPage.descriptionPlaceholder": "e.g., Summer Sale Flyer",
    "qrcodesPage.descriptionMax": "Description must be at most 255 characters",
    "qrcodesPage.qrNamePlaceholder": "e.g., Summer Sale Flyer",
    "qrcodesPage.destinationUrlLabel": "Destination URL",
    "qrcodesPage.urlPlaceholder": "https://example.com",
    "qrcodesPage.qrType": "QR Type",
    "qrcodesPage.staticUrl": "Static URL",
    "qrcodesPage.dynamicQr": "Dynamic QR",
    "qrcodesPage.vcard": "vCard (Contact)",
    "qrcodesPage.trackingAnalytics": "Tracking & Analytics",
    "qrcodesPage.useCampaignDefault": "Use Campaign Default",
    "qrcodesPage.trackingInherited": "Uses the tracking ID inherited from",
    "qrcodesPage.manualEntry": "Manual Entry",
    "qrcodesPage.autoDetect": "Auto-detect",
    "qrcodesPage.linkedGoogleAccount": "Linked Google Account",
    "qrcodesPage.connectGoogleFirst": "Connect Google in",
    "qrcodesPage.selectGa4Property": "Select a GA4 property...",
    "qrcodesPage.utmSettings": "UTM Settings",
    "qrcodesPage.utmSource": "UTM Source",
    "qrcodesPage.utmMedium": "UTM Medium",
    "qrcodesPage.utmCampaign": "UTM Campaign",
    "qrcodesPage.utmCampaignPlaceholder": "Enter UTM campaign",
    "qrcodesPage.syncUtmCampaign": "Sync utm_campaign with QR name",
    "qrcodesPage.tracking": "Tracking",
    "qrcodesPage.default": "Default",
    "qrcodesPage.editQRCodeTitle": "Edit QR Code",
    "qrcodesPage.editQRCodeSubtitle": "Update QR code details and settings",
    "qrcodesPage.loadingQrCodeData": "Loading QR code data...",
    "qrcodesPage.editLoadErrorForbidden": "You do not have permission to view this QR code.",
    "qrcodesPage.editLoadErrorInvalidSession": "Your login session is not valid.",
    "qrcodesPage.editLoadError": "Unable to load QR code detail.",
    "qrcodesPage.qrCodeNotFound": "QR code not found",
    "qrcodesPage.backToQRCodes": "Back to QR Codes",
    "qrcodesPage.campaignInfo": "Campaign Information",
    "qrcodesPage.campaignInfoDesc": "This QR code belongs to the following campaign",
    "qrcodesPage.configureBasicInfo": "Configure the basic information for your QR code",
    "qrcodesPage.ga4Tracking": "GA4 Tracking",
    "qrcodesPage.configureAnalyticsAndTracking": "Configure analytics and tracking for this QR code",
    "qrcodesPage.campaignGa4Configured": "Campaign GA4: Configured",
    "qrcodesPage.campaignGa4NotConfigured": "Campaign GA4: Not configured",
    "qrcodesPage.enableTracking": "Enable tracking for this QR",
    "qrcodesPage.useCampaignTrackingCode": "Use campaign tracking code",
    "qrcodesPage.noTrackingCodeConfigured": "No tracking code configured for this campaign",
    "qrcodesPage.useCustomTrackingCode": "Use custom tracking code",
    "qrcodesPage.enterGa4MeasurementId": "Enter GA4 Measurement ID (e.g., G-XXXXXXXXXX)",
    "qrcodesPage.useTrackingCodeFromGoogleAccount": "Use tracking code from Google account",
    "qrcodesPage.recommended": "Recommended",
    "qrcodesPage.connectGoogleFirstMessage": "To use this feature, connect your Google account",
    "qrcodesPage.connectGoogleAccount": "Connect Google Account",
    "qrcodesPage.unableToLoadGa4PropertiesReconnect": "Unable to load GA4 properties. Please reconnect your account.",
    "qrcodesPage.reconnectAccount": "Reconnect Account",
    "qrcodesPage.googleAccountConnected": "Google account connected",
    "qrcodesPage.loadingGa4Properties": "Loading GA4 properties...",
    "qrcodesPage.unableToLoadGa4Properties": "Unable to load GA4 properties.",
    "qrcodesPage.urlPreview": "URL Preview",
    "qrcodesPage.summary": "Summary",
    "qrcodesPage.noCampaignSelected": "Not selected",
    "qrcodesPage.type": "Type",
    "qrcodesPage.saving": "Saving...",
    "qrcodesPage.saveQrCode": "Save QR Code",
    "qrcodesPage.previewDescription": "QR code preview will appear here",
    "qrcodesPage.validation.qrNameMin": "QR Name must be at least 3 characters",
    "qrcodesPage.validation.qrNameRequired": "QR Name is required",
    "qrcodesPage.validation.selectCampaign": "Please select a campaign",
    "qrcodesPage.validation.descriptionMax": "Description must be at most 255 characters",
    "qrcodesPage.validation.destinationUrlRequired": "Destination URL is required",
    "qrcodesPage.validation.validUrl": "Please enter a valid URL",
    "qrcodesPage.ga4Detected": "Detected GA4: {{id}}",
    "qrcodesPage.noGa4Found": "No GA4 ID found on this link.",
    "qrcodesPage.enterUrlFirst": "Please enter a URL first",
    "qrcodesPage.createSuccess": "QR Code created!",
    "qrcodesPage.createError": "Failed to create QR Code",
    "qrcodesPage.invalidGa4Format": "Invalid G-XXXXXXXXXX format",

    // Create Campaign Form
    "createCampaign.title": "Create Campaign",
    "createCampaign.subtitle": "Set up a new QR code marketing campaign. Fill in the details below to get started.",
    "createCampaign.pageSubtitle": "Set up a new campaign to track and manage QR codes",
    "createCampaign.campaignName": "Campaign Name",
    "createCampaign.campaignNamePlaceholder": "e.g., Summer Sale 2024",
    "createCampaign.status": "Status",
    "createCampaign.draft": "Draft",
    "createCampaign.active": "Active",
    "createCampaign.paused": "Paused",
    "createCampaign.dateRange": "Campaign Date Range",
    "createCampaign.startDate": "Start Date",
    "createCampaign.endDate": "End Date",
    "createCampaign.description": "Description",
    "createCampaign.descriptionOptional": "Description (Optional)",
    "createCampaign.descriptionPlaceholder": "Add campaign details, goals, target audience...",
    "createCampaign.cancel": "Cancel",
    "createCampaign.creating": "Creating...",
    "createCampaign.create": "Create Campaign",
    "createCampaign.nameError": "Campaign name must be at least 3 characters.",
    "createCampaign.startDateError": "Start date is required.",
    "createCampaign.endDateError": "End date is required.",
    "createCampaign.endDateAfterStartError": "End date must be on or after start date",
    "createCampaign.createError": "Failed to create campaign. Please try again.",

    // Create QR Code Page
    "createQR.title": "Create QR Code",
    "createQR.subtitle": "Create a new QR code for your campaign",
    "createQR.selectCampaign": "Select Campaign",
    "createQR.selectCampaignDesc": "Choose which campaign this QR code will belong to",
    "createQR.selectCampaignPlaceholder": "Select a campaign...",
    "createQR.noCampaignsTitle": "No Campaigns Found",
    "createQR.noCampaignsDesc": "You need to create a campaign before you can create QR codes. QR codes are always associated with a campaign for tracking and organization.",
    "createQR.createFirstCampaign": "Create Your First Campaign",
    "createQR.qrDetails": "QR Code Details",
    "createQR.qrDetailsDesc": "Configure the basic information for your QR code",
    "createQR.qrName": "QR Code Name",
    "createQR.qrNamePlaceholder": "e.g., Homepage Banner, Product Page Link",
    "createQR.destinationUrl": "Destination URL",
    "createQR.destinationUrlPlaceholder": "https://example.com/landing-page",
    "createQR.urlType": "URL Type",
    "createQR.staticUrl": "Static URL",
    "createQR.dynamicUrl": "Dynamic URL",
    "createQR.vcard": "vCard (Contact)",
    "createQR.trackingSettings": "Tracking Settings",
    "createQR.trackingSettingsDesc": "Configure analytics and tracking for this QR code",
    "createQR.ga4Tracking": "GA4 Tracking",
    "createQR.ga4Configured": "Campaign GA4: Configured",
    "createQR.ga4NotConfigured": "Campaign GA4: Not configured",
    "createQR.enableTracking": "Enable tracking for this QR",
    "createQR.useCampaignTracking": "Use campaign tracking code",
    "createQR.noTrackingCode": "No tracking code configured for this campaign",
    "createQR.useCustomTracking": "Use custom tracking code",
    "createQR.customTrackingPlaceholder": "Enter GA4 Measurement ID (e.g., G-XXXXXXXXXX)",
    "createQR.useGoogleAccount": "Use tracking code from Google account",
    "createQR.recommended": "Recommended",
    "createQR.connectGooglePrompt": "To use this feature, connect your Google account",
    "createQR.connectGoogle": "Connect Google Account",
    "createQR.googleLoadError": "Unable to load GA4 properties. Please reconnect your account.",
    "createQR.retryConnection": "Retry Connection",
    "createQR.selectGa4Property": "Select GA4 property",
    "createQR.utmParameters": "UTM Parameters",
    "createQR.utmSource": "UTM Source",
    "createQR.utmMedium": "UTM Medium",
    "createQR.utmCampaign": "UTM Campaign",
    "createQR.syncWithQrName": "Sync with QR code name",
    "createQR.urlPreview": "URL Preview",
    "createQR.preview": "Preview",
    "createQR.previewDesc": "Preview of your QR code",
    "createQR.createQR": "Create QR Code",
    "createQR.campaignRequired": "Please select a campaign",
    "createQR.nameRequired": "QR Code name is required",
    "createQR.nameTooShort": "QR Code name must be at least 3 characters",
    "createQR.urlRequired": "Destination URL is required",
    "createQR.urlInvalid": "Please enter a valid URL",

    // Dashboard Overview
    "overview.title": "Global Overview",
    "overview.subtitle": "System-wide metrics and campaign performance across all QR campaigns",
    "overview.totalScans": "Total Scans",
    "overview.activeCampaigns": "Active Campaigns",
    "overview.totalUniqueUsers": "Total Unique Users",
    "overview.systemGrowth": "System Growth",
    "overview.allCampaignsCombined": "All campaigns combined",
    "overview.currentlyRunning": "Currently running",
    "overview.acrossAllCampaigns": "Across all campaigns",
    "overview.monthOverMonth": "Month over month",
    "overview.vsLastPeriod": "vs last period",
    "overview.scansPerCampaign": "Scans per Campaign",
    "overview.topPerforming": "Top performing campaigns by total scans",
    "overview.trafficDistribution": "Traffic Distribution",
    "overview.trafficPercentage": "Percentage of traffic across campaigns",
    "overview.allCampaigns": "All Campaigns",
    "overview.allCampaignsDesc": "Complete list of QR campaigns in your system",
    "overview.searchCampaigns": "Search campaigns...",
    "overview.campaignName": "Campaign Name",
    "overview.totalScansCol": "Total Scans",
    "overview.uniqueUsers": "Unique Users",
    "overview.seeAnalytics": "See analytics",
    "overview.noCampaignsFound": "No campaigns found.",

    // Table Pagination
    "pagination.rowsPerPage": "Rows per page",
    "pagination.of": "of",
    "pagination.page": "Page",

    // Auth
    "auth.login": "Login",
    "auth.register": "Register",
    "auth.logout": "Log out",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.confirmPassword": "Confirm Password",
    "auth.forgotPassword": "Forgot Password?",
    "auth.noAccount": "Don't have an account?",
    "auth.hasAccount": "Already have an account?",
    "auth.signUp": "Sign Up",
    "auth.signIn": "Sign In",

    // Integrations Setup
    "integrations.setup.title": "Google Services Setup",
    "integrations.setup.subtitle": "Manage your Google service connections for calendar sync and analytics tracking",
    "integrations.setup.connectionStatus": "Connection Status",
    "integrations.setup.connectionStatusDesc": "Overall status of your Google services integration",
    "integrations.setup.connectedToGoogle": "Connected to Google",
    "integrations.setup.setup": "Setup",
    "integrations.setup.switchAccount": "Switch Account",
    "integrations.setup.disconnect": "Disconnect",
    "integrations.setup.disconnectTitle": "Disconnect Google Services?",
    "integrations.setup.disconnectDesc": "This action will remove all access to QRFlow's Calendar and Analytics",
    "integrations.setup.serviceDetails": "Service Details",
    "integrations.setup.serviceDetailsDesc": "Individual connection status for each Google service",
    "integrations.setup.account": "Account",
    "integrations.setup.lastSynced": "Last synced",
    "integrations.status.connected": "Connected",
    "integrations.status.disconnected": "Disconnected",
    "integrations.status.error": "Error",
    "integrations.status.allConnected": "All services connected",
    "integrations.status.noneConnected": "No services connected",
    "integrations.status.partialConnected": "{count} of {total} services connected",
    "integrations.status.allConnectedDesc": "Your Google account is linked for both Calendar and Analytics services",
    "integrations.status.noneConnectedDesc": "Connect your Google account to enable calendar sync and more",
    "integrations.status.partialConnectedDesc": "Some services require attention",

    // Accounts/Employees Page
    "accounts.title": "Employee List",
    "accounts.subtitle": "Manage system users and view their activity statistics",
    "accounts.allEmployees": "All Employees",
    "accounts.allEmployeesDesc": "View and manage all users with access to the system",
    "accounts.searchPlaceholder": "Search by username or email...",
    "accounts.allRoles": "All Roles",
    "accounts.admin": "Admin",
    "accounts.employee": "Employee",
    "accounts.username": "Username",
    "accounts.role": "Role",
    "accounts.campaignsCreated": "Campaigns Created",
    "accounts.qrCodesCreated": "QR Codes Created",
    "accounts.createdAt": "Created At",
    "accounts.noEmployees": "No employees found",
    "accounts.loadingEmployees": "Loading employees...",
    "accounts.loadError": "Failed to load employees. Please try refreshing the page.",
    "accounts.deleteTitle": "Delete Employee",
    "accounts.deleteConfirm": "Are you sure you want to delete",
    "accounts.deleteWarning": "This action cannot be undone and will remove all their data from the system.",
    "accounts.deleteEmployee": "Delete Employee",

    // Employee Detail Page
    "employeeDetail.backToList": "Back to Employee List",
    "employeeDetail.memberSince": "Member since",
    "employeeDetail.admin": "Admin",
    "employeeDetail.employee": "Employee",
    "employeeDetail.saveChanges": "Save Changes",
    "employeeDetail.accountInfo": "Account Information",
    "employeeDetail.accountInfoDesc": "View and edit employee account details",
    "employeeDetail.accountName": "Account Name",
    "employeeDetail.fullName": "Full Name",
    "employeeDetail.phoneNumber": "Phone Number",
    "employeeDetail.email": "Email",
    "employeeDetail.campaignsCreated": "Campaigns Created",
    "employeeDetail.qrCodesCreated": "QR Codes Created",
    "employeeDetail.campaignsCount": "campaign(s) created by this employee",
    "employeeDetail.qrCodesCount": "QR code(s) created by this employee",
    "employeeDetail.noCampaigns": "No campaigns created yet",
    "employeeDetail.noQRCodes": "No QR codes created yet",
    "employeeDetail.campaignName": "Campaign Name",
    "employeeDetail.status": "Status",
    "employeeDetail.created": "Created",
    "employeeDetail.qrCodeName": "QR Code Name",
    "employeeDetail.scans": "Scans",
    "employeeDetail.employeeNotFound": "Employee not found",

    // Campaign Detail Page
    "campaignDetail.campaignDetails": "Campaign Details",
    "campaignDetail.clickToEdit": "Click on any field to edit",
    "campaignDetail.timeline": "Timeline",
    "campaignDetail.startDate": "Start Date",
    "campaignDetail.endDate": "End Date",
    "campaignDetail.selectStartDate": "Select start date",
    "campaignDetail.selectEndDate": "Select end date",
    "campaignDetail.addDescription": "Click to add a description...",
    "campaignDetail.trackingActive": "Tracking Active",
    "campaignDetail.noTracking": "No Tracking",
    "campaignDetail.connected": "Connected",
    "campaignDetail.syncRequired": "Sync Required",
    "campaignDetail.syncDescription": "Calendar events need to be synchronized with Google Calendar.",
    "campaignDetail.syncToCalendar": "Sync to Google Calendar",
    "campaignDetail.ga4Config": "Google Analytics 4 Configuration",
    "campaignDetail.ga4ConfigDesc": "Configure GA4 tracking for this campaign",
    "campaignDetail.useConnectedAccount": "Use Connected Account",
    "campaignDetail.oauthDescription": "Load GA4 properties via backend using your app JWT + stored OAuth token.",
    "campaignDetail.ga4Default": "GA4 Default",
    "campaignDetail.ga4DefaultDesc": "Set a campaign default tracking code (you can still override per QR).",
    "campaignDetail.saveGa4Settings": "Save GA4 Settings",
    "campaignDetail.itemsActive": "items active",
    "campaignDetail.createNewQr": "Create New QR",
    "campaignDetail.addQrToCampaign": "Add a new QR code to this campaign",
    "campaignDetail.createQr": "Create QR",
    "campaignDetail.updateQrDetails": "Update the QR code details and tracking settings",
    "campaignDetail.trackingStatus": "Tracking Status",
    "campaignDetail.enabled": "Enabled",
    "campaignDetail.disabled": "Disabled",
    "campaignDetail.openRedirectUrl": "Open Redirect URL",
    "campaignDetail.noQrCodesYet": "No QR codes yet",
    "campaignDetail.createFirstQr": "Create your first QR code for this campaign.",
  },
  vi: {
    // Navigation
    "nav.dashboard": "Bảng điều khiển",
    "nav.campaign": "Chiến dịch",
    "nav.campaign.list": "Danh sách",
    "nav.campaign.create": "Tạo mới",
    "nav.qrcode": "Mã QR",
    "nav.qrcode.list": "Danh sách",
    "nav.qrcode.create": "Tạo mới",
    "nav.ggServices": "Dịch vụ GG",
    "nav.ggServices.setup": "Cài đặt",
    "nav.ggServices.sync": "Đồng bộ lên Lịch",
    "nav.ggServices.import": "Nhập từ Lịch",
    "nav.ggServices.remove": "Xóa sự kiện",
    "nav.analytics": "Phân tích",
    "nav.analytics.campaign": "Phân tích theo Chiến dịch",
    "nav.report": "Báo cáo",
    "nav.report.export": "Xuất báo cáo cho Khách hàng",
    "nav.accountManagement": "Quản lý Tài khoản",
    "nav.accountManagement.employees": "Danh sách Nhân viên",
    "nav.navigation": "Điều hướng",

     // User Menu
     "user.profile": "Hồ sơ",
     "user.settings": "Cài đặt",
     "user.toggleTheme": "Giao diện",
     "user.switchLanguage": "Ngôn ngữ",
     "user.logout": "Đăng xuất",
     "user.language.en": "Tiếng Anh",
     "user.language.vi": "Tiếng Việt",

    // Breadcrumbs
    "breadcrumb.home": "Trang chủ",
    "breadcrumb.dashboard": "Bảng điều khiển",
    "breadcrumb.campaigns": "Chiến dịch",
    "breadcrumb.googleServices": "Dịch vụ Google",
    "breadcrumb.reports": "Báo cáo",
    "breadcrumb.qrcodes": "Mã QR",
    "breadcrumb.settings": "Cài đặt",
    "breadcrumb.accounts": "Tài khoản",
    "breadcrumb.employees": "Nhân viên",
    "breadcrumb.create": "Tạo mới",
    "breadcrumb.setup": "Cài đặt",
    "breadcrumb.sync": "Đồng bộ",
    "breadcrumb.import": "Nhập",
    "breadcrumb.undo": "Hoàn tác",
    "breadcrumb.export": "Xuất",

    // Common
    "common.notifications": "Thông báo",
    "common.search": "Tìm kiếm",
    "common.save": "Lưu",
    "common.cancel": "Hủy",
    "common.delete": "Xóa",
    "common.edit": "Sửa",
    "common.create": "Tạo",
    "common.loading": "Đang tải...",
    "common.noData": "Không có dữ liệu",
    "common.actions": "Thao tác",
    "common.status": "Trạng thái",
    "common.name": "Tên",
    "common.description": "Mô tả",
    "common.date": "Ngày",
    "common.active": "Hoạt động",
    "common.inactive": "Không hoạt động",
    "common.paused": "Tạm dừng",
    "common.completed": "Hoàn thành",
    "common.planned": "Đã lập kế hoạch",
    "common.all": "Tất cả",
    "common.filter": "Lọc",
    "common.export": "Xuất",
    "common.import": "Nhập",
    "common.refresh": "Làm mới",
    "common.back": "Quay lại",
    "common.next": "Tiếp theo",
    "common.previous": "Trước đó",
    "common.submit": "Gửi",
    "common.reset": "Đặt lại",
    "common.close": "Đóng",
    "common.confirm": "Xác nhận",
    "common.yes": "Có",
    "common.no": "Không",
    "common.pro": "Pro",
    "common.preview": "Xem trước",
    "common.enabled": "Đã bật",
    "common.disabled": "Đã tắt",

    // Dashboard
    "dashboard.title": "Bảng điều khiển",
    "dashboard.welcome": "Chào mừng trở lại",
    "dashboard.overview": "Tổng quan",
    "dashboard.totalCampaigns": "Tổng số Chiến dịch",
    "dashboard.activeQRCodes": "Mã QR Hoạt động",
    "dashboard.totalScans": "Tổng lượt Quét",
    "dashboard.recentActivity": "Hoạt động Gần đây",

    // Campaigns
    "campaigns.title": "Chiến dịch",
    "campaigns.create": "Tạo Chiến dịch",
    "campaigns.edit": "Sửa Chiến dịch",
    "campaigns.delete": "Xóa Chiến dịch",
    "campaigns.name": "Tên Chiến dịch",
    "campaigns.status": "Trạng thái",
    "campaigns.startDate": "Ngày bắt đầu",
    "campaigns.endDate": "Ngày kết thúc",
    "campaigns.scans": "Lượt quét",
    "campaigns.qrCodes": "Mã QR",
    "campaigns.noResults": "Không tìm thấy chiến dịch",

    // QR Codes
    "qrcodes.title": "Mã QR",
    "qrcodes.create": "Tạo Mã QR",
    "qrcodes.edit": "Sửa Mã QR",
    "qrcodes.delete": "Xóa Mã QR",
    "qrcodes.download": "Tải xuống",
    "qrcodes.preview": "Xem trước",
    "qrcodes.scans": "Tổng lượt Quét",
    "qrcodes.destination": "URL Đích",
    "qrcodes.noResults": "Không tìm thấy mã QR",

    // Settings
    "settings.title": "Cài đặt",
    "settings.subtitle": "Quản lý cài đặt tài khoản và tùy chọn của bạn",
    "settings.profile": "Thông tin Hồ sơ",
    "settings.profileDesc": "Cập nhật thông tin cá nhân và chi tiết liên hệ của bạn",
    "settings.account": "Tài khoản",
    "settings.notifications": "Tùy chọn Thông báo",
    "settings.notificationsDesc": "Chọn loại thông báo bạn muốn nhận",
    "settings.language": "Ngôn ngữ",
    "settings.theme": "Giao diện",
    "settings.username": "Tên đăng nhập",
    "settings.fullName": "Họ và Tên",
    "settings.phone": "Số điện thoại",
    "settings.email": "Email",
    "settings.saveChanges": "Lưu thay đổi",
    "settings.changePassword": "Đổi mật khẩu",
    "settings.changePasswordDesc": "Cập nhật mật khẩu để bảo mật tài khoản của bạn",
    "settings.currentPassword": "Mật khẩu hiện tại",
    "settings.newPassword": "Mật khẩu mới",
    "settings.confirmNewPassword": "Xác nhận mật khẩu mới",
    "settings.updatePassword": "Cập nhật mật khẩu",
    "settings.emailAlerts": "Thông báo Email",
    "settings.emailAlertsDesc": "Nhận thông báo email cho các cập nhật quan trọng",
    "settings.campaignUpdates": "Cập nhật Chiến dịch",
    "settings.campaignUpdatesDesc": "Nhận thông báo khi chiến dịch được tạo hoặc sửa đổi",
    "settings.weeklyReports": "Báo cáo Hàng tuần",
    "settings.weeklyReportsDesc": "Nhận bản tóm tắt hiệu suất chiến dịch hàng tuần",
    "settings.dangerZone": "Vùng Nguy hiểm",
    "settings.dangerZoneDesc": "Các hành động không thể hoàn tác cho tài khoản của bạn",
    "settings.logoutDesc": "Đăng xuất khỏi tài khoản của bạn",
    "settings.logoutSubDesc": "Bạn sẽ được chuyển hướng đến trang đăng nhập",
    "settings.logoutConfirmTitle": "Bạn có chắc chắn muốn đăng xuất?",
    "settings.logoutConfirmDesc": "Bạn sẽ cần đăng nhập lại để truy cập bảng điều khiển.",
    "settings.passwordIncorrect": "Mật khẩu hiện tại không đúng",
    "settings.passwordTooShort": "Mật khẩu mới phải có ít nhất 8 ký tự",
    "settings.passwordMismatch": "Mật khẩu mới không khớp",

    // Campaigns Page
    "campaignsPage.title": "Chiến dịch",
    "campaignsPage.subtitle": "Quản lý và theo dõi các chiến dịch marketing mã QR của bạn",
    "campaignsPage.createCampaign": "Tạo Chiến dịch",
    "campaignsPage.searchPlaceholder": "Tìm theo tên, mô tả hoặc người tạo...",
    "campaignsPage.allStatus": "Tất cả Trạng thái",
    "campaignsPage.active": "Hoạt động",
    "campaignsPage.paused": "Tạm dừng",
    "campaignsPage.campaignName": "Tên Chiến dịch",
    "campaignsPage.createdBy": "Tạo bởi",
    "campaignsPage.createAt": "Tạo ngày",
    "campaignsPage.dateRange": "Khoảng thời gian",
    "campaignsPage.integrations": "Tích hợp",
    "campaignsPage.calendar": "Lịch",
    "campaignsPage.viewDetails": "Xem chi tiết",
    "campaignsPage.editCampaign": "Sửa Chiến dịch",
    "campaignsPage.deleteCampaign": "Xóa Chiến dịch",
    "campaignsPage.deleteTitle": "Xóa Chiến dịch",
    "campaignsPage.deleteConfirm": "Bạn có chắc chắn muốn xóa",
    "campaignsPage.deleteWarning": "Hành động này không thể hoàn tác.",
    "campaignsPage.noCampaigns": "Không tìm thấy chiến dịch",

    // QR Codes Page
    "qrcodesPage.title": "Mã QR",
    "qrcodesPage.subtitle": "Quản lý và theo dõi tất cả mã QR của bạn trong các chiến dịch",
    "qrcodesPage.createQRCode": "Tạo Mã QR",
    "qrcodesPage.searchPlaceholder": "Tìm theo tên, URL hoặc chiến dịch...",
    "qrcodesPage.allCampaigns": "Tất cả Chiến dịch",
    "qrcodesPage.allStatus": "Tất cả Trạng thái",
    "qrcodesPage.active": "Hoạt động",
    "qrcodesPage.inactive": "Không hoạt động",
    "qrcodesPage.createdBy": "Người tạo",
    "qrcodesPage.qrCodeName": "Tên Mã QR",
    "qrcodesPage.campaign": "Chiến dịch",
    "qrcodesPage.destinationUrl": "URL Đích",
    "qrcodesPage.scans": "Lượt quét",
    "qrcodesPage.unique": "duy nhất",
    "qrcodesPage.created": "Tạo lúc",
    "qrcodesPage.lastScan": "Quét lần cuối",
    "qrcodesPage.viewQRCode": "Xem Mã QR",
    "qrcodesPage.downloadQRCode": "Tải xuống Mã QR",
    "qrcodesPage.copyLink": "Sao chép liên kết",
    "qrcodesPage.copied": "Đã sao chép!",
    "qrcodesPage.editQRCode": "Sửa Mã QR",
    "qrcodesPage.deleteQRCode": "Xóa Mã QR",
    "qrcodesPage.deleteTitle": "Xóa Mã QR",
    "qrcodesPage.deleteConfirm": "Bạn có chắc chắn muốn xóa mã QR này?",
    "qrcodesPage.deleteWarning": "Hành động này không thể hoàn tác.",
    "qrcodesPage.noQRCodes": "Không tìm thấy mã QR",
    "qrcodesPage.qrDetails": "Chi tiết Mã QR",
    "qrcodesPage.downloadPng": "Tải xuống PNG",
    "qrcodesPage.downloadSvg": "Tải xuống SVG",
    "qrcodesPage.scanQr": "Quét để truy cập URL",

    // Create QR Form (additional keys)
    "qrcodesPage.selectCampaign": "Chọn Chiến dịch",
    "qrcodesPage.selectCampaignPlaceholder": "Chọn một chiến dịch",
    "qrcodesPage.qrCodeDetails": "Chi tiết Mã QR",
    "qrcodesPage.qrCodeNameLabel": "Tên Mã QR",
    "qrcodesPage.qrNamePlaceholder": "VD: Tờ rơi Khuyến mãi Hè",
    "qrcodesPage.descriptionLabel": "Chi tiết mã QR",
    "qrcodesPage.descriptionPlaceholder": "VD: Mã Qr hiện tại đang được sử dụng",
    "qrcodesPage.descriptionMax": "Chi tiết mã QR không được vượt quá 255 ký tự",
    "qrcodesPage.destinationUrlLabel": "URL Đích",
    "qrcodesPage.urlPlaceholder": "https://example.com",
    "qrcodesPage.qrType": "Loại Mã QR",
    "qrcodesPage.staticUrl": "URL Tĩnh",
    "qrcodesPage.dynamicQr": "Mã QR Động",
    "qrcodesPage.vcard": "vCard (Liên hệ)",
    "qrcodesPage.trackingAnalytics": "Theo dõi & Phân tích",
    "qrcodesPage.useCampaignDefault": "Sử dụng Mặc định Chiến dịch",
    "qrcodesPage.trackingInherited": "Sử dụng ID theo dõi kế thừa từ",
    "qrcodesPage.manualEntry": "Nhập Thủ công",
    "qrcodesPage.autoDetect": "Tự động phát hiện",
    "qrcodesPage.linkedGoogleAccount": "Tài khoản Google đã liên kết",
    "qrcodesPage.connectGoogleFirst": "Kết nối Google trong",
    "qrcodesPage.selectGa4Property": "Chọn thuộc tính GA4...",
    "qrcodesPage.utmSettings": "Cài đặt UTM",
    "qrcodesPage.utmSource": "Nguồn UTM",
    "qrcodesPage.utmMedium": "Phương tiện UTM",
    "qrcodesPage.utmCampaign": "Chiến dịch UTM",
    "qrcodesPage.utmCampaignPlaceholder": "Nhập chiến dịch UTM",
    "qrcodesPage.syncUtmCampaign": "Đồng bộ utm_campaign với tên QR",
    "qrcodesPage.tracking": "Theo dõi",
    "qrcodesPage.default": "Mặc định",
    "qrcodesPage.editQRCodeTitle": "Sửa Mã QR",
    "qrcodesPage.editQRCodeSubtitle": "Cập nhật chi tiết và cài đặt mã QR",
    "qrcodesPage.loadingQrCodeData": "Đang tải dữ liệu mã QR...",
    "qrcodesPage.editLoadErrorForbidden": "Bạn không có quyền xem mã QR này.",
    "qrcodesPage.editLoadErrorInvalidSession": "Phiên đăng nhập của bạn không hợp lệ.",
    "qrcodesPage.editLoadError": "Không thể tải chi tiết mã QR.",
    "qrcodesPage.qrCodeNotFound": "Không tìm thấy mã QR",
    "qrcodesPage.backToQRCodes": "Quay lại Mã QR",
    "qrcodesPage.campaignInfo": "Thông tin Chiến dịch",
    "qrcodesPage.campaignInfoDesc": "Mã QR này thuộc về chiến dịch sau",
    "qrcodesPage.configureBasicInfo": "Cấu hình thông tin cơ bản cho mã QR của bạn",
    "qrcodesPage.ga4Tracking": "Theo dõi GA4",
    "qrcodesPage.configureAnalyticsAndTracking": "Cấu hình phân tích và theo dõi cho mã QR này",
    "qrcodesPage.campaignGa4Configured": "GA4 chiến dịch: Đã cấu hình",
    "qrcodesPage.campaignGa4NotConfigured": "GA4 chiến dịch: Chưa cấu hình",
    "qrcodesPage.enableTracking": "Bật theo dõi cho mã QR này",
    "qrcodesPage.useCampaignTrackingCode": "Dùng mã theo dõi của chiến dịch",
    "qrcodesPage.noTrackingCodeConfigured": "Chưa có mã theo dõi nào được cấu hình cho chiến dịch này",
    "qrcodesPage.useCustomTrackingCode": "Dùng mã theo dõi tùy chỉnh",
    "qrcodesPage.enterGa4MeasurementId": "Nhập Measurement ID GA4 (VD: G-XXXXXXXXXX)",
    "qrcodesPage.useTrackingCodeFromGoogleAccount": "Dùng mã theo dõi từ tài khoản Google",
    "qrcodesPage.recommended": "Đề xuất",
    "qrcodesPage.connectGoogleFirstMessage": "Để sử dụng tính năng này, hãy kết nối tài khoản Google của bạn",
    "qrcodesPage.connectGoogleAccount": "Kết nối tài khoản Google",
    "qrcodesPage.unableToLoadGa4PropertiesReconnect": "Không thể tải thuộc tính GA4. Vui lòng kết nối lại tài khoản của bạn.",
    "qrcodesPage.reconnectAccount": "Kết nối lại",
    "qrcodesPage.googleAccountConnected": "Tài khoản Google đã được kết nối",
    "qrcodesPage.loadingGa4Properties": "Đang tải thuộc tính GA4...",
    "qrcodesPage.unableToLoadGa4Properties": "Không thể tải thuộc tính GA4.",
    "qrcodesPage.urlPreview": "Xem trước URL",
    "qrcodesPage.summary": "Tóm tắt",
    "qrcodesPage.noCampaignSelected": "Chưa chọn",
    "qrcodesPage.type": "Loại",
    "qrcodesPage.saving": "Đang lưu...",
    "qrcodesPage.saveQrCode": "Lưu Mã QR",
    "qrcodesPage.previewDescription": "Xem trước mã QR sẽ hiển thị ở đây",
    "qrcodesPage.validation.qrNameRequired": "Vui lòng nhập tên QR",
    "qrcodesPage.validation.qrNameMin": "Tên QR phải có ít nhất 3 ký tự",
    "qrcodesPage.validation.selectCampaign": "Vui lòng chọn một chiến dịch",
    "qrcodesPage.validation.descriptionMax": "Chi tiết mã QR không được vượt quá 255 ký tự",
    "qrcodesPage.validation.destinationUrlRequired": "Vui lòng nhập URL đích",
    "qrcodesPage.validation.validUrl": "Vui lòng nhập URL hợp lệ",
    "qrcodesPage.ga4Detected": "Đã phát hiện GA4: {{id}}",
    "qrcodesPage.noGa4Found": "Không tìm thấy ID GA4 trên liên kết này.",
    "qrcodesPage.enterUrlFirst": "Vui lòng nhập URL trước",
    "qrcodesPage.createSuccess": "Đã tạo Mã QR!",
    "qrcodesPage.createError": "Không thể tạo Mã QR",
    "qrcodesPage.invalidGa4Format": "Định dạng G-XXXXXXXXXX không hợp lệ",

    // Create Campaign Form
    "createCampaign.title": "Tạo Chiến dịch",
    "createCampaign.subtitle": "Thiết lập chiến dịch marketing mã QR mới. Điền thông tin bên dưới để bắt đầu.",
    "createCampaign.pageSubtitle": "Thiết lập chiến dịch mới để theo dõi và quản lý mã QR",
    "createCampaign.campaignName": "Tên Chiến dịch",
    "createCampaign.campaignNamePlaceholder": "VD: Khuyến mãi Hè 2024",
    "createCampaign.status": "Trạng thái",
    "createCampaign.draft": "Bản nháp",
    "createCampaign.active": "Hoạt động",
    "createCampaign.paused": "Tạm dừng",
    "createCampaign.dateRange": "Khoảng thời gian Chiến dịch",
    "createCampaign.startDate": "Ngày bắt đầu",
    "createCampaign.endDate": "Ngày kết thúc",
    "createCampaign.description": "Mô tả",
    "createCampaign.descriptionOptional": "Mô tả (Tùy chọn)",
    "createCampaign.descriptionPlaceholder": "Thêm chi tiết chiến dịch, mục tiêu, đối tượng...",
    "createCampaign.cancel": "Hủy",
    "createCampaign.creating": "Đang tạo...",
    "createCampaign.create": "Tạo Chiến dịch",
    "createCampaign.nameError": "Tên chiến dịch phải có ít nhất 3 ký tự.",
    "createCampaign.startDateError": "Ngày bắt đầu là bắt buộc.",
    "createCampaign.endDateError": "Ngày kết thúc là bắt buộc.",
    "createCampaign.endDateAfterStartError": "Ngày kết thúc phải sau hoặc bằng ngày bắt đầu",
    "createCampaign.createError": "Không thể tạo chiến dịch. Vui lòng thử lại.",

    // Create QR Code Page
    "createQR.title": "Tạo Mã QR",
    "createQR.subtitle": "Tạo mã QR mới cho chiến dịch của bạn",
    "createQR.selectCampaign": "Chọn Chiến dịch",
    "createQR.selectCampaignDesc": "Chọn chiến dịch mà mã QR này sẽ thuộc về",
    "createQR.selectCampaignPlaceholder": "Chọn một chiến dịch...",
    "createQR.noCampaignsTitle": "Không tìm thấy Chiến dịch",
    "createQR.noCampaignsDesc": "Bạn cần tạo chiến dịch trước khi có thể tạo mã QR. Mã QR luôn được liên kết với chiến dịch để theo dõi và tổ chức.",
    "createQR.createFirstCampaign": "Tạo Chiến dịch Đầu tiên",
    "createQR.qrDetails": "Chi tiết Mã QR",
    "createQR.qrDetailsDesc": "Cấu hình thông tin cơ bản cho mã QR của bạn",
    "createQR.qrName": "Tên Mã QR",
    "createQR.qrNamePlaceholder": "VD: Banner Trang chủ, Liên kết Sản phẩm",
    "createQR.destinationUrl": "URL Đích",
    "createQR.destinationUrlPlaceholder": "https://example.com/trang-dich",
    "createQR.urlType": "Loại URL",
    "createQR.staticUrl": "URL Tĩnh",
    "createQR.dynamicUrl": "URL Động",
    "createQR.vcard": "vCard (Liên hệ)",
    "createQR.trackingSettings": "Cài đặt Theo dõi",
    "createQR.trackingSettingsDesc": "Cấu hình phân tích và theo dõi cho mã QR này",
    "createQR.ga4Tracking": "Theo dõi GA4",
    "createQR.ga4Configured": "GA4 Chiến dịch: Đã cấu hình",
    "createQR.ga4NotConfigured": "GA4 Chiến dịch: Chưa cấu hình",
    "createQR.enableTracking": "Bật theo dõi cho mã QR này",
    "createQR.useCampaignTracking": "Sử dụng mã theo dõi chiến dịch",
    "createQR.noTrackingCode": "Chưa cấu hình mã theo dõi cho chiến dịch này",
    "createQR.useCustomTracking": "Sử dụng mã theo dõi tùy chỉnh",
    "createQR.customTrackingPlaceholder": "Nhập GA4 Measurement ID (VD: G-XXXXXXXXXX)",
    "createQR.useGoogleAccount": "Sử dụng mã theo dõi từ tài khoản Google",
    "createQR.recommended": "Khuyến nghị",
    "createQR.connectGooglePrompt": "Để sử dụng tính năng này, hãy kết nối tài khoản Google của bạn",
    "createQR.connectGoogle": "Kết nối Tài khoản Google",
    "createQR.googleLoadError": "Không thể tải thuộc tính GA4. Vui lòng kết nối lại tài khoản.",
    "createQR.retryConnection": "Thử lại Kết nối",
    "createQR.selectGa4Property": "Chọn thuộc tính GA4",
    "createQR.utmParameters": "Tham số UTM",
    "createQR.utmSource": "UTM Source",
    "createQR.utmMedium": "UTM Medium",
    "createQR.utmCampaign": "UTM Campaign",
    "createQR.syncWithQrName": "Đồng bộ với tên mã QR",
    "createQR.urlPreview": "Xem trước URL",
    "createQR.preview": "Xem trước",
    "createQR.previewDesc": "Xem trước mã QR của bạn",
    "createQR.createQR": "Tạo Mã QR",
    "createQR.campaignRequired": "Vui lòng chọn một chiến dịch",
    "createQR.nameRequired": "Tên mã QR là bắt buộc",
    "createQR.nameTooShort": "Tên mã QR phải có ít nhất 3 ký tự",
    "createQR.urlRequired": "URL đích là bắt buộc",
    "createQR.urlInvalid": "Vui lòng nhập URL hợp lệ",

    // Dashboard Overview
    "overview.title": "Tổng quan Hệ thống",
    "overview.subtitle": "Số liệu toàn hệ thống và hiệu suất chiến dịch qua tất cả các chiến dịch QR",
    "overview.totalScans": "Tổng lượt Quét",
    "overview.activeCampaigns": "Chiến dịch Hoạt động",
    "overview.totalUniqueUsers": "Tổng Người dùng Duy nhất",
    "overview.systemGrowth": "Tăng trưởng Hệ thống",
    "overview.allCampaignsCombined": "Tất cả chiến dịch kết hợp",
    "overview.currentlyRunning": "Đang chạy",
    "overview.acrossAllCampaigns": "Qua tất cả chiến dịch",
    "overview.monthOverMonth": "So với tháng trước",
    "overview.vsLastPeriod": "so với kỳ trước",
    "overview.scansPerCampaign": "Lượt Quét theo Chiến dịch",
    "overview.topPerforming": "Các chiến dịch hoạt động tốt nhất theo tổng lượt quét",
    "overview.trafficDistribution": "Phân bố Lưu lượng",
    "overview.trafficPercentage": "Phần trăm lưu lượng qua các chiến dịch",
    "overview.allCampaigns": "Tất cả Chiến dịch",
    "overview.allCampaignsDesc": "Danh sách đầy đủ các chiến dịch QR trong hệ thống của bạn",
    "overview.searchCampaigns": "Tìm kiếm chiến dịch...",
    "overview.campaignName": "Tên Chiến dịch",
    "overview.totalScansCol": "Tổng lượt Quét",
    "overview.uniqueUsers": "Người dùng Duy nhất",
    "overview.seeAnalytics": "Xem phân tích",
    "overview.noCampaignsFound": "Không tìm thấy chiến dịch.",

    // Table Pagination
    "pagination.rowsPerPage": "Số hàng mỗi trang",
    "pagination.of": "của",
    "pagination.page": "Trang",

    // Auth
    "auth.login": "Đăng nhập",
    "auth.register": "Đăng ký",
    "auth.logout": "Đăng xuất",
    "auth.email": "Email",
    "auth.password": "Mật khẩu",
    "auth.confirmPassword": "Xác nhận Mật khẩu",
    "auth.forgotPassword": "Quên mật khẩu?",
    "auth.noAccount": "Chưa có tài khoản?",
    "auth.hasAccount": "Đã có tài khoản?",
    "auth.signUp": "Đăng ký",
    "auth.signIn": "Đăng nhập",

    // Integrations Setup
    "integrations.setup.title": "Cài đặt Dịch vụ Google",
    "integrations.setup.subtitle": "Quản lý kết nối dịch vụ Google cho đồng bộ lịch và theo dõi phân tích",
    "integrations.setup.connectionStatus": "Trạng thái Kết nối",
    "integrations.setup.connectionStatusDesc": "Trạng thái tổng thể của tích hợp dịch vụ Google",
    "integrations.setup.connectedToGoogle": "Đã kết nối Google",
    "integrations.setup.setup": "Cài đặt",
    "integrations.setup.switchAccount": "Chuyển Tài khoản",
    "integrations.setup.disconnect": "Ngắt kết nối",
    "integrations.setup.disconnectTitle": "Ngắt kết nối Dịch vụ Google?",
    "integrations.setup.disconnectDesc": "Hành động này sẽ xóa tất cả quyền truy cập vào Lịch và Phân tích của QRFlow",
    "integrations.setup.serviceDetails": "Chi tiết Dịch vụ",
    "integrations.setup.serviceDetailsDesc": "Trạng thái kết nối riêng lẻ cho từng dịch vụ Google",
    "integrations.setup.account": "Tài khoản",
    "integrations.setup.lastSynced": "Đồng bộ lần cuối",
    "integrations.status.connected": "Đã kết nối",
    "integrations.status.disconnected": "Chưa kết nối",
    "integrations.status.error": "Lỗi",
    "integrations.status.allConnected": "Tất cả dịch vụ đã kết nối",
    "integrations.status.noneConnected": "Chưa có dịch vụ nào kết nối",
    "integrations.status.partialConnected": "{count} trong {total} dịch vụ đã kết nối",
    "integrations.status.allConnectedDesc": "Tài khoản Google của bạn đã liên kết cho cả dịch vụ Lịch và Phân tích",
    "integrations.status.noneConnectedDesc": "Kết nối tài khoản Google để bật đồng bộ lịch và nhiều tính năng khác",
    "integrations.status.partialConnectedDesc": "Một số dịch vụ cần được chú ý",

    // Accounts/Employees Page
    "accounts.title": "Danh sách Nhân viên",
    "accounts.subtitle": "Quản lý người dùng hệ thống và xem thống kê hoạt động",
    "accounts.allEmployees": "Tất cả Nhân viên",
    "accounts.allEmployeesDesc": "Xem và quản lý tất cả người dùng có quyền truy cập hệ thống",
    "accounts.searchPlaceholder": "Tìm theo tên đăng nhập hoặc email...",
    "accounts.allRoles": "Tất cả Vai trò",
    "accounts.admin": "Quản trị viên",
    "accounts.employee": "Nhân viên",
    "accounts.username": "Tên đăng nhập",
    "accounts.role": "Vai trò",
    "accounts.campaignsCreated": "Chiến dịch Đã tạo",
    "accounts.qrCodesCreated": "Mã QR Đã tạo",
    "accounts.createdAt": "Ngày tạo",
    "accounts.noEmployees": "Không tìm thấy nhân viên",
    "accounts.loadingEmployees": "Đang tải nhân viên...",
    "accounts.loadError": "Không thể tải nhân viên. Vui lòng thử làm mới trang.",
    "accounts.deleteTitle": "Xóa Nhân viên",
    "accounts.deleteConfirm": "Bạn có chắc chắn muốn xóa",
    "accounts.deleteWarning": "Hành động này không thể hoàn tác và sẽ xóa tất cả dữ liệu của họ khỏi hệ thống.",
    "accounts.deleteEmployee": "Xóa Nhân viên",

    // Employee Detail Page
    "employeeDetail.backToList": "Quay lại Danh sách Nhân viên",
    "employeeDetail.memberSince": "Thành viên từ",
    "employeeDetail.admin": "Quản trị viên",
    "employeeDetail.employee": "Nhân viên",
    "employeeDetail.saveChanges": "Lưu thay đổi",
    "employeeDetail.accountInfo": "Thông tin Tài khoản",
    "employeeDetail.accountInfoDesc": "Xem và chỉnh sửa thông tin tài khoản nhân viên",
    "employeeDetail.accountName": "Tên tài khoản",
    "employeeDetail.fullName": "Họ và Tên",
    "employeeDetail.phoneNumber": "Số điện thoại",
    "employeeDetail.email": "Email",
    "employeeDetail.campaignsCreated": "Chiến dịch Đã tạo",
    "employeeDetail.qrCodesCreated": "Mã QR Đã tạo",
    "employeeDetail.campaignsCount": "chiến dịch được tạo bởi nhân viên này",
    "employeeDetail.qrCodesCount": "mã QR được tạo bởi nhân viên này",
    "employeeDetail.noCampaigns": "Chưa có chiến dịch nào được tạo",
    "employeeDetail.noQRCodes": "Chưa có mã QR nào được tạo",
    "employeeDetail.campaignName": "Tên Chiến dịch",
    "employeeDetail.status": "Trạng thái",
    "employeeDetail.created": "Ngày tạo",
    "employeeDetail.qrCodeName": "Tên Mã QR",
    "employeeDetail.scans": "Lượt quét",
    "employeeDetail.employeeNotFound": "Không tìm thấy nhân viên",

    // Campaign Detail Page
    "campaignDetail.campaignDetails": "Chi tiết Chiến dịch",
    "campaignDetail.clickToEdit": "Nhấp vào bất kỳ trường nào để chỉnh sửa",
    "campaignDetail.timeline": "Thời gian",
    "campaignDetail.startDate": "Ngày bắt đầu",
    "campaignDetail.endDate": "Ngày kết thúc",
    "campaignDetail.selectStartDate": "Chọn ngày bắt đầu",
    "campaignDetail.selectEndDate": "Chọn ngày kết thúc",
    "campaignDetail.addDescription": "Nhấp để thêm mô tả...",
    "campaignDetail.trackingActive": "Đang theo dõi",
    "campaignDetail.noTracking": "Chưa theo dõi",
    "campaignDetail.connected": "Đã kết nối",
    "campaignDetail.syncRequired": "Cần đồng bộ",
    "campaignDetail.syncDescription": "Các sự kiện lịch cần được đồng bộ với Google Calendar.",
    "campaignDetail.syncToCalendar": "Đồng bộ với Google Calendar",
    "campaignDetail.ga4Config": "Cấu hình Google Analytics 4",
    "campaignDetail.ga4ConfigDesc": "Cấu hình theo dõi GA4 cho chiến dịch này",
    "campaignDetail.useConnectedAccount": "Sử dụng Tài khoản Đã kết nối",
    "campaignDetail.oauthDescription": "Tải thuộc tính GA4 qua backend sử dụng app JWT + OAuth token đã lưu.",
    "campaignDetail.ga4Default": "GA4 Mặc định",
    "campaignDetail.ga4DefaultDesc": "Đặt mã theo dõi mặc định cho chiến dịch (bạn vẫn có thể ghi đè cho từng QR).",
    "campaignDetail.saveGa4Settings": "Lưu cài đặt GA4",
    "campaignDetail.itemsActive": "mục đang hoạt động",
    "campaignDetail.createNewQr": "Tạo QR Mới",
    "campaignDetail.addQrToCampaign": "Thêm mã QR mới vào chiến dịch này",
    "campaignDetail.createQr": "Tạo QR",
    "campaignDetail.updateQrDetails": "Cập nhật chi tiết mã QR và cài đặt theo dõi",
    "campaignDetail.trackingStatus": "Trạng thái Theo dõi",
    "campaignDetail.enabled": "Đã bật",
    "campaignDetail.disabled": "Đã tắt",
    "campaignDetail.openRedirectUrl": "Mở URL Chuyển hướng",
    "campaignDetail.noQrCodesYet": "Chưa có mã QR",
    "campaignDetail.createFirstQr": "Tạo mã QR đầu tiên cho chiến dịch này.",
  },
}

const LanguageContext = React.createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = React.useState<Language>("en")

  React.useEffect(() => {
    // Load saved language preference from localStorage
    const savedLanguage = localStorage.getItem("language") as Language
    if (savedLanguage && (savedLanguage === "en" || savedLanguage === "vi")) {
      setLanguageState(savedLanguage)
    }
  }, [])

  const setLanguage = React.useCallback((lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem("language", lang)
  }, [])

  const t = React.useCallback(
    (key: string): string => {
      return translations[language][key] || key
    },
    [language]
  )

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = React.useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
